skinny-framework/skinny-framework

orm/src/main/scala/skinny/orm/feature/IncludesFeature.scala, orm/src/test/scala/issue219/ByDefaultSpec.scala, orm/src/test/scala/issue219/Issue219Spec.scala
=> Fix #219 findById with #includes doesn't return a result as expected when assocations are absent

framework/src/main/scala/skinny/controller/feature/ValidationFeature.scala
These methods should be reusable for framework users.
=> Move errorMessages/keyAndErrorMessages builder to companion

yeoman-generator-skinny/app/templates/build.sbt, yeoman-generator-skinny/app/templates/project/Build.scala, yeoman-generator-skinny/app/templates/project/plugins.sbt, yeoman-generator-skinny/app/templates/skinny, yeoman-generator-skinny/app/templates/skinny.bat
=> Fix #237 scoverage 1.0 migration issue

common/src/main/scala/skinny/ParamType.scala, common/src/test/scala/skinny/ParamTypeSpec.scala, orm/src/test/scala/skinny/orm/feature/StrongParametersFeatureSpec.scala
ParamType.String,DateTime,LocalDate,LocalTime consider empty string as null.
=> ParamType improvements

example/src/main/scala/controller/BacklogController.scala, example/src/main/scala/controller/BacklogJPController.scala, example/src/main/scala/controller/Controllers.scala, example/src/main/webapp/WEB-INF/views/backlog/ok.html.ssp, oauth2-controller/src/main/scala/skinny/controller/feature/BacklogJPLoginFeature.scala, oauth2-controller/src/main/scala/skinny/controller/feature/BacklogLoginFeature.scala, oauth2/src/main/scala/skinny/oauth2/client/OAuth2Provider.scala, oauth2/src/main/scala/skinny/oauth2/client/backlog/BacklogAPI.scala, oauth2/src/main/scala/skinny/oauth2/client/backlog/BacklogJPAPI.scala, oauth2/src/main/scala/skinny/oauth2/client/backlog/BacklogUser.scala
Backlog is a project management service from @nulab.
http://backlogtool.com/
http://developer.nulab-inc.com/docs/backlog/auth
=> Backlog OAuth 2.0 support

framework/src/main/scala/skinny/controller/SkinnyApiResourceActions.scala, framework/src/main/scala/skinny/controller/SkinnyResourceActions.scala
And fix related scaladocs.
Is this a bug?
=> Add a missing parameter. pageSize(Actual name is "size").

orm/src/main/scala/skinny/orm/feature/AssociationsFeature.scala, orm/src/main/scala/skinny/orm/feature/associations/Associations.scala, orm/src/test/scala/test007/Spec.scala
=> Fix pagination with hasMany+byDefault doesn't work as expected

orm/src/main/scala/skinny/orm/feature/AssociationsFeature.scala, orm/src/main/scala/skinny/orm/feature/CRUDFeature.scala, orm/src/main/scala/skinny/orm/feature/JoinsFeature.scala, orm/src/main/scala/skinny/orm/feature/NoIdJoinsFeature.scala, orm/src/main/scala/skinny/orm/feature/associations/Associations.scala
Re-fix https://github.com/skinny-framework/skinny-framework/pull/243 in a better way. @namutaka Thanks again.
=> Re-fix pagination with has many by default

orm/src/main/scala/skinny/orm/feature/FinderFeature.scala, orm/src/test/scala/issue263/Issue263Spec.scala
=> Fix #263 findAllByWithLimitOffset doesn't work with child condition

engine/src/main/scala/skinny/engine/ApiFormats.scala, engine/src/main/scala/skinny/engine/ContentEncodingSupport.scala, engine/src/main/scala/skinny/engine/SkinnyEngineBase.scala, engine/src/main/scala/skinny/engine/SkinnyEngineFilter.scala, engine/src/main/scala/skinny/engine/async/AsyncResult.scala, engine/src/main/scala/skinny/engine/async/FutureSupport.scala, engine/src/main/scala/skinny/engine/base/CoreHandler.scala, engine/src/main/scala/skinny/engine/base/FlashMapSupport.scala, engine/src/main/scala/skinny/engine/base/SkinnyEngineContextInitializer.scala, engine/src/main/scala/skinny/engine/context/SkinnyEngineContext.scala, engine/src/main/scala/skinny/engine/csrf/CsrfTokenSupport.scala, engine/src/main/scala/skinny/engine/csrf/XsrfTokenSupport.scala, engine/src/main/scala/skinny/engine/i18n/I18nSupport.scala, engine/src/main/scala/skinny/engine/json/JsonOutput.scala, engine/src/main/scala/skinny/engine/json/JsonSupport.scala, engine/src/main/scala/skinny/engine/request/StableHttpServletRequest.scala, engine/src/main/scala/skinny/engine/routing/CoreRoutingDsl.scala, engine/src/main/scala/skinny/engine/scalate/ScalateI18nSupport.scala, engine/src/main/scala/skinny/engine/scalate/ScalateSupport.scala, engine/src/main/scala/skinny/engine/scalate/ScalateUrlGeneratorSupport.scala, engine/src/main/scala/skinny/engine/scalate/SkinnyEngineRenderContext.scala, engine/src/test/scala/org/scalatra/scalate/ScalateFuturesSupportSpec.scala, example/src/main/scala/controller/DashboardController.scala, framework/src/main/scala/skinny/controller/SkinnyControllerBase.scala, framework/src/main/scala/skinny/controller/feature/FutureOpsFeature.scala, framework/src/main/scala/skinny/controller/feature/JSONParamsAutoBinderFeature.scala, framework/src/main/scala/skinny/controller/feature/RequestScopeFeature.scala, framework/src/main/scala/skinny/controller/feature/ScalateTemplateEngineFeature.scala, test/src/main/scala/skinny/test/MockControllerBase.scala, thymeleaf/src/main/scala/skinny/controller/feature/ThymeleafTemplateEngineFeature.scala
Finally, this pull request removes the dynamic scope issue from skinny-engine.
=> Get rid of dynamic scope

engine/src/main/scala/skinny/engine/base/ParamsAccessor.scala, engine/src/main/scala/skinny/engine/data/MultiMapHeadView.scala, engine/src/main/scala/skinny/engine/request/RichRequest.scala, engine/src/test/scala/org/scalatra/PatchSpec.scala
Fixes https://github.com/scalatra/scalatra/issues/531
=> params and multiParams are empty for PATCH request

framework/src/main/scala/skinny/session/jdbc/SkinnySession.scala, framework/src/main/scala/skinny/session/jdbc/SkinnySessionAttribute.scala, orm/src/main/scala/skinny/orm/SkinnyNoIdMapper.scala, orm/src/main/scala/skinny/orm/feature/AssociationsFeature.scala, orm/src/main/scala/skinny/orm/feature/associations/Extractors.scala, orm/src/test/scala/issue259/Spec.scala
This pull request fixes the issue described in pull request #259. The following things will be allowed.
- hasOne relationship with NoIdMapper
- hasMany relationship with NoIdMapper
cc @danieletorelli
=> Enable to define hasOne/hasMany relations with NoIdMapper

framework/src/main/scala/skinny/session/jdbc/SkinnySession.scala, framework/src/main/scala/skinny/session/jdbc/SkinnySessionAttribute.scala, orm/src/main/scala/skinny/orm/SkinnyNoIdMapper.scala, orm/src/main/scala/skinny/orm/feature/AssociationsFeature.scala, orm/src/main/scala/skinny/orm/feature/associations/Extractors.scala, orm/src/test/scala/issue259/Spec.scala
This pull request backports #287 for 1.3.x releases.
=> backport: Enable to define hasOne/hasMany relations with NoIdMapper #287

.travis.yml, framework/src/test/scala/skinny/SkinnySpec.scala, framework/src/test/scala/skinny/controller/feature/ScalateTemplateEngineFeaturespec.scala, project/Build.scala, project/plugins.sbt, publish.sh, skinny, test/src/main/scala/skinny/test/MockControllerBase.scala, travis.sh
- scala minor update
- libs minor upgrade
- skinny micro 0.9.14
- update travis settings
=> Bump dependencies, scala version

project/Build.scala
https://flywaydb.org/blog/flyway-4.0
=> Bump Flyway version to 4.0

factory-girl/src/main/scala/skinny/test/FactoryGirl.scala, factory-girl/src/test/resources/foo bar baz/post2.conf, factory-girl/src/test/scala/whitespace/BlogSpec.scala, factory-girl/src/test/scala/whitespace/Connection.scala, factory-girl/src/test/scala/whitespace/CreateTables.scala, factory-girl/src/test/scala/whitespace/Post.scala, factory-girl/src/test/scala/whitespace/PostTag.scala, factory-girl/src/test/scala/whitespace/Tag.scala
This pull request fixes the #322 issue.
=> Fix #322 FactoryGirl cannot find factories directory when '%20' appears in the path

task/src/main/scala/skinny/task/generator/ModelGenerator.scala, task/src/main/scala/skinny/task/generator/ReverseScaffoldAllGenerator.scala, task/src/test/scala/skinny/task/generator/ReverseScaffoldAllGenerator_Inflector2Spec.scala, task/src/test/scala/skinny/task/generator/ReverseScaffoldAllGenerator_reservedWordsSpec.scala
This pull request fixes the still existing issue on join table names (e.g.) CustomFieldsRole.scala
=> Re-fix #328 implementation

example/src/main/scala/controller/CommentsController.scala, example/src/main/scala/controller/Controllers.scala, example/src/main/webapp/WEB-INF/assets/jsx/comment-box.jsx, example/src/main/webapp/WEB-INF/assets/jsx/hello-react.jsx, example/src/main/webapp/WEB-INF/layouts/angular.ssp, example/src/main/webapp/WEB-INF/layouts/bar.scaml, example/src/main/webapp/WEB-INF/layouts/default.html, example/src/main/webapp/WEB-INF/layouts/default.scaml, example/src/main/webapp/WEB-INF/layouts/simple/foo.scaml, example/src/main/webapp/WEB-INF/views/comments/show.html.jade, example/src/main/webapp/WEB-INF/views/react/index.html.ssp, example/src/main/webapp/WEB-INF/views/root/index.html.ssp, example/src/test/scala/integrationtest/AssetsSpec.scala, skinny-blank-app/src/main/webapp/WEB-INF/layouts/default.html, skinny-blank-app/src/main/webapp/WEB-INF/layouts/default.ssp
This pull request bumps minor version of Bootstrap and jQuery that are embedded in the default layout template. NOTE: Bootstrap can work with jQuery 2.x.
=> Bump bootstrap, jQuery minor version

build.sbt, project/plugins.sbt, skinny-blank-app/build.sbt, skinny-blank-app/project/plugins.sbt
sbt-scalate-precompiler has been moved to scalate organization.
- https://github.com/skinny-framework/sbt-scalate-precompiler 
- https://github.com/scalate/sbt-scalate-precompiler
=> Move to scalate/sbt-scalate-precompiler

orm/src/main/scala/skinny/orm/feature/IncludesFeature.scala, orm/src/test/scala/issue346/Issue347Spec.scala
=> Fix #347 includes + hasMany doesn't work with non-default primaryKeyFieldName

task/src/main/scala/skinny/task/generator/ScaffoldJadeGenerator.scala, task/src/main/scala/skinny/task/generator/ScaffoldScamlGenerator.scala, task/src/main/scala/skinny/task/generator/ScaffoldSspGenerator.scala, task/src/test/scala/skinny/task/generator/ReverseScaffoldAllGeneratorSpec.scala, task/src/test/scala/skinny/task/generator/ReverseScaffoldAllGenerator_Inflector2Spec.scala, task/src/test/scala/skinny/task/generator/ReverseScaffoldAllGenerator_InflectorSpec.scala, task/src/test/scala/skinny/task/generator/ReverseScaffoldAllGenerator_reservedWordsSpec.scala, task/src/test/scala/skinny/task/generator/ScaffoldJadeGeneratorSpec.scala, task/src/test/scala/skinny/task/generator/ScaffoldScamlGeneratorSpec.scala, task/src/test/scala/skinny/task/generator/ScaffoldSspGeneratorSpec.scala
This pull request changes the behavior of the view template generator to have new button on the top of index pages as well.
=> Add new button on the top

task/src/main/scala/skinny/task/generator/ScaffoldJadeGenerator.scala, task/src/main/scala/skinny/task/generator/ScaffoldScamlGenerator.scala, task/src/main/scala/skinny/task/generator/ScaffoldSspGenerator.scala, task/src/test/scala/skinny/task/generator/ReverseScaffoldAllGeneratorSpec.scala, task/src/test/scala/skinny/task/generator/ReverseScaffoldAllGenerator_Inflector2Spec.scala, task/src/test/scala/skinny/task/generator/ReverseScaffoldAllGenerator_InflectorSpec.scala, task/src/test/scala/skinny/task/generator/ReverseScaffoldAllGenerator_reservedWordsSpec.scala, task/src/test/scala/skinny/task/generator/ScaffoldJadeGeneratorSpec.scala, task/src/test/scala/skinny/task/generator/ScaffoldScamlGeneratorSpec.scala, task/src/test/scala/skinny/task/generator/ScaffoldSspGeneratorSpec.scala
This pull request improves the UI introduced by #350.
=> Re-fix #350 from seratch/new-button-on-the-top

.travis.yml, build.sbt, example/src/test/scala/integrationtest/RootControllerSpec.scala, framework/src/main/scala/skinny/session/jdbc/SkinnySession.scala, framework/src/test/scala/skinny/session/SkinnySessionSpec.scala, orm/src/main/scala/skinny/orm/JodaImplicits.scala, orm/src/main/scala/skinny/orm/SkinnyMapperBase.scala, orm/src/main/scala/skinny/orm/feature/CRUDFeature.scala, orm/src/test/scala/skinny/orm/Connection.scala, orm/src/test/scala/skinny/orm/SkinnyORMSpec.scala, project/plugins.sbt, publish_local.sh, skinny-blank-app/build.sbt, skinny-blank-app/project/plugins.sbt, travis.sh
This pull request applies necessary changes for 2.6.0. If everything seems fine, I will release skinny-micro 1.3.0 final.
=> Updates for 2.6.0 migration

.travis.yml, build.sbt, orm/src/test/scala/skinny/orm/models.scala, publish.sh, publish_local.sh, skinny-blank-app/build.sbt, travis.sh
fix https://github.com/skinny-framework/skinny-framework/issues/372
=> Scala 2.12.6

.travis.yml, build.sbt, project/build.properties, skinny-blank-app/build.sbt, skinny-blank-app/project/build.properties
After merging this, I will release version 3.0.1.
=> Bump sbt, scala 2.12 to the latest patch versions

travis.sh
https://scalameta.org/scalafmt/docs/installation.html#task-keys
=> run test:scalafmtCheck

skinny-blank-app/sbt-launch-lib.bash, skinny-blank-app/sbt.bat
https://qiita.com/Lettuce222/items/36dd90af7d6921fea96d
=> java9-rt-export.jar no longer needed
