framework/src/main/scala/org/scalatra/SkinnyScalatraBase.scala
=> Fix #222 java.lang.InternalError when using doubly nested class name (SI-2034) since 1.3.6

common/src/main/scala/skinny/activeimplicits/AllImplicits.scala, common/src/main/scala/skinny/activeimplicits/NumberImplicits.scala, common/src/main/scala/skinny/activeimplicits/StringImplicits.scala, common/src/main/scala/skinny/nlp/KuromojiJapaneseAnalyzer.scala, common/src/main/scala/skinny/nlp/SkinnyJapaneseAnalyzer.scala, common/src/main/scala/skinny/nlp/SkinnyJapaneseAnalyzerFactory.scala, common/src/main/scala/skinny/util/StringUtil.scala, common/src/test/scala/skinny/activeimplicits/AllImplicitsSpec.scala, common/src/test/scala/skinny/activeimplicits/NumberImplicitsSpec.scala, common/src/test/scala/skinny/activeimplicits/StringImplicitsSpec.scala, common/src/test/scala/skinny/nlp/SkinnyJapaneseAnalyzerSpec.scala, common/src/test/scala/skinny/util/StringUtilSpec.scala, project/Build.scala, project/build.properties
Here is an ActiveSupport-ish implicit conversions module. 
http://guides.rubyonrails.org/active_support_core_extensions.html
Currently following classes are extended. Features which require inflections are not supported yet.
- String
- Int/Long/Double/BigDecimal
```scala
import skinny.activeimplicits.NumberImplicits._
100.kilobytes should equal(102400.bytes)
3.weeks should equal(21.days)
import skinny.activeimplicits.StringImplicits._
"Donald E. Knuth".parameterize should equal("donald-e-knuth")
"x-men: the last stand".titleize should equal("X Men: The Last Stand")
// prerequisite: Apache Lucene Kuromoji Analyzer
"東京特許許可局".hiragana should equal("とうきょうとっきょきょかきょく")
"ようかい体操第一".katakana should equal("ヨウカイタイソウダイイチ")
"地獄のミサワ".romaji should equal("jigokunomisawa")
```
=> ActiveSupport-ish implicit conversions

framework/src/main/scala/skinny/controller/SkinnyControllerBase.scala, framework/src/main/scala/skinny/controller/feature/FormParamsFeature.scala, framework/src/main/scala/skinny/controller/feature/QueryParamsFeature.scala, framework/src/test/scala/skinny/controller/feature/FormParamsFeatureSpec.scala, framework/src/test/scala/skinny/controller/feature/QueryParamsFeatureSpec.scala
This pull request newly enables following four APIs.
- queryParams
- queryMultiParams
- formParams
- formMultiParams
Although some people may wonder why Scalatra doesn't support these APIs, I think that's reasonable because sinatra doesn't have them.
=> Add query(Multi)Params and form(Multi)Params

orm/src/main/scala/skinny/orm/feature/QueryingFeature.scala, orm/src/test/scala/issue229/Issue229Spec.scala, orm/src/test/scala/skinny/orm/servlet/TxPerRequestFilterSpec.scala
This pull request fixes #229 [orm] where('col_name -> Nil) condition is removed.
=> Fix #229 [orm] where('col_name -> Nil) condition is removed

oauth2/src/main/scala/skinny/oauth2/client/google/GoogleUser.scala
I was testing the GoogleLoginFeature with a Google user with no URL and I was getting the following error:
```
2015-02-04 03:15:32.628 ERROR   --- [tp1815007640-68] s.oauth2.client.google.GooglePlusAPI$    : Failed to get current Google user information because No usable value for url
Did not find value which can be converted into java.lang.String
org.json4s.package$MappingException: No usable value for url
Did not find value which can be converted into java.lang.String
```
This should fix it.
=> URL field should be optional

run_skinny-blank-app_test.sh, yeoman-generator-skinny/app/templates/skinny, yeoman-generator-skinny/app/templates/skinny.bat, yeoman-generator-skinny/app/templates/src/main/webapp/WEB-INF/assets/build.sbt
refs #231
Scala.js 0.6.0 will be out on Feb. 5th.  https://github.com/scala-js/scala-js-website/pull/114
scalajs-dom and scalajs-jquery are re-organized. scalajs-jasmine-test-framework has been removed.
=> Scala.js 0.6.0

orm/src/test/scala/skinny/orm/servlet/TxPerRequestFilterSpec.scala, orm/src/test/scala/test006/Spec.scala, project/Build.scala, project/plugins.sbt, travis_after.sh, yeoman-generator-skinny/app/templates/project/Build.scala, yeoman-generator-skinny/app/templates/project/plugins.sbt
Unfortunately, xsbt-scalate-generate is no longer actively maintained. 
Compiling Scalate templates is a very important part of Skinny apps development. So I just decided to fork the project and keep maintaining it. 
This forked project aims to achieve the following benefits.
- Control of release management
- Smooth upgrade corresponded to the lastest Scalate libs
- Reduce the number of dependencies when bootstrapping new Skinny projects
Forked project is already available on sonatype snapshots repository. Please try it out and give us your feedback.
https://github.com/skinny-framework/sbt-scalate-precompiler
=> Switch xsbt-scalate-generator to sbt-scalate-precompiler

framework/src/main/scala/skinny/controller/feature/EnvFeature.scala, framework/src/test/scala/skinny/controller/feature/EnvFeatureSpec.scala
Scalatra default is upper case. But Skinny is expect lower case.
Therefore add the convert process.
=> Fix env handling.

framework/src/main/scala/org/scalatra/SkinnyScalatraBase.scala, framework/src/main/scala/skinny/filter/SkinnyFilterActivation.scala, framework/src/test/scala/skinny/filter/SkinnyFilterActivationSpec.scala
Possible memory leak issue has been found by @rinoguchi. Due to current implementation which calls the following method lots of times, 
https://github.com/scalatra/scalatra/blob/v2.3.1/core/src/main/scala/org/scalatra/ScalatraBase.scala#L333-L335
`errorHandler` in ScalatraBase unnecessarily becomes enlarged.
https://github.com/scalatra/scalatra/blob/v2.3.1/core/src/main/scala/org/scalatra/ScalatraBase.scala#L329-L331
This pull request fixes the issue. Next version including this fix should be out soon.
=> Fix memory leak at SkinnyFilterActivation

framework/src/main/scala/skinny/filter/SkinnyFilterActivation.scala
I think it's better to call `error()` method outside of `beforeAction`.
=> Refix memory leak at SkinnyFilterActivation (Pull #257)

yeoman-generator-skinny/app/templates/project/Build.scala
Since Java options are passed to the process (the first one would be the Java process that SBT lives in), one needs to fork a new process to run tests in order to read the `-Dskinny.env=test` property.
=> Add fork in Test to generated Build.scala

project/Build.scala, project/plugins.sbt, yeoman-generator-skinny/app/templates/project/Build.scala, yeoman-generator-skinny/app/templates/project/plugins.sbt
xsbt-web-plugin 1.x has some issues for skinny. sbt-servlet-plugin is a fork of xsbt-web-plugin 0.9 and I've renamed most of things.
https://github.com/skinny-framework/sbt-servlet-plugin
=> Switch to sbt-servlet-plugin

engine/src/main/scala/skinny/engine/SkinnyEngineBase.scala, engine/src/main/scala/skinny/engine/SkinnyEngineBasicFeatures.scala, engine/src/main/scala/skinny/engine/SkinnyEngineFilter.scala, engine/src/main/scala/skinny/engine/SkinnyEngineServlet.scala, engine/src/main/scala/skinny/engine/csrf/CsrfTokenSupport.scala, engine/src/main/scala/skinny/engine/csrf/XsrfTokenSupport.scala, engine/src/main/scala/skinny/engine/i18n/I18nSupport.scala, engine/src/main/scala/skinny/engine/routing/AsyncRoutingDsl.scala, engine/src/main/scala/skinny/engine/scalate/ScalateI18nSupport.scala, engine/src/test/scala/org/scalatra/AfterTest.scala, framework/src/main/scala/skinny/controller/SkinnyControllerBase.scala, framework/src/main/scala/skinny/controller/feature/BeforeAfterActionFeature.scala, framework/src/main/scala/skinny/controller/feature/FlashFeature.scala, framework/src/main/scala/skinny/controller/feature/RequestScopeFeature.scala
SkinnyEngineBase itself should be slim as much as possible to enable users their own base trait.
=> Remove BeforeAfter, JsonOperations from SkinnyEngineBase

engine/src/main/scala/skinny/engine/Handler.scala, engine/src/main/scala/skinny/engine/SkinnyEngineBase.scala, engine/src/main/scala/skinny/engine/SkinnyEngineListener.scala, engine/src/main/scala/skinny/engine/UnstableAccessException.scala, engine/src/main/scala/skinny/engine/UnstableAccessValidation.scala, engine/src/main/scala/skinny/engine/async/AsyncResult.scala, engine/src/main/scala/skinny/engine/base/FlashMapSupport.scala, engine/src/main/scala/skinny/engine/base/MainThreadLocalEverywhere.scala, engine/src/main/scala/skinny/engine/base/SkinnyEngineContextInitializer.scala, engine/src/main/scala/skinny/engine/base/UnstableAccessValidationConfig.scala, engine/src/main/scala/skinny/engine/context/SkinnyEngineContext.scala, engine/src/main/scala/skinny/engine/request/StableHttpServletRequest.scala, engine/src/main/scala/skinny/engine/routing/AsyncRoutingDsl.scala, engine/src/main/scala/skinny/engine/routing/RoutingDsl.scala, engine/src/test/scala/example/StableRequestSpec.scala, engine/src/test/scala/org/scalatra/scalate/ScalateFuturesSupportSpec.scala, framework/src/main/scala/skinny/filter/SkinnyFilter.scala, framework/src/main/scala/skinny/filter/SkinnySessionFilter.scala, framework/src/test/scala/skinny/SkinnySpec.scala, project/Build.scala, test/src/main/scala/skinny/controller/SessionInjectorController.scala, test/src/main/scala/skinny/controller/SkinnySessionInjectorController.scala, test/src/main/scala/skinny/test/MockControllerBase.scala, yeoman-generator-skinny/app/templates/project/Build.scala
This pull request introduces UnstableAccessValidation to detect unstable access to objects managed by containers.
=> UnstableAccessValidation to detect unstable access

engine/src/main/scala/skinny/engine/base/SkinnyEngineContextInitializer.scala, engine/src/main/scala/skinny/engine/scalate/ScalateSupport.scala, engine/src/test/scala/example/HelloSpec.scala
This pull request introduces thread id validation to detect `MainThreadLocalEverywhere` access from other threads. 
Previously the dynamic scope issue didn't easily become obvious. With this detection introduced by this PR, it will be easier to detect the issue can happen due to some invalid code than now.
=> Add thread id validation to detect illegal dynamic scope access more

engine/src/main/scala/skinny/engine/request/EncodedInputStream.scala, engine/src/main/scala/skinny/engine/request/StableHttpServletRequest.scala, engine/src/main/scala/skinny/engine/response/EncodedOutputStream.scala, engine/src/main/scala/skinny/engine/response/EncodedServletResponse.scala, framework/src/main/scala/skinny/session/servlet/SkinnyHttpRequestWrapper.scala, project/Build.scala
There is no specific reason for us to drop Servlet 3.0 right now.
=> Keep supporting Servlet 3.0 for now

framework/src/main/scala/skinny/controller/SkinnyApiResourceActions.scala, framework/src/main/scala/skinny/controller/feature/AngularXSRFProtectionFeature.scala, framework/src/main/scala/skinny/controller/feature/CORSFeature.scala, framework/src/main/scala/skinny/controller/feature/CSRFProtectionFeature.scala, framework/src/main/scala/skinny/controller/feature/JSONFeature.scala, framework/src/main/scala/skinny/controller/feature/JSONParamsAutoBinderFeature.scala, framework/src/main/scala/skinny/controller/feature/TemplateEngineFeature.scala, framework/src/main/scala/skinny/controller/feature/ThreadLocalRequestFeature.scala, framework/src/main/scala/skinny/controller/feature/XContentTypeOptionsNosniffHeaderFeature.scala, framework/src/main/scala/skinny/controller/feature/XFrameOptionsHeaderFeature.scala, framework/src/main/scala/skinny/controller/feature/XXSSProtectionHeaderFeature.scala, framework/src/test/scala/skinny/controller/feature/BeforeAfterFeatureSpec.scala, framework/src/test/scala/skinny/controller/feature/JSONFeatureSpec.scala, json/src/main/scala/skinny/json/package.scala, json/src/test/scala/skinny/util/JSONStringOpsSpec.scala, oauth2/src/main/scala/skinny/oauth2/client/backlog/BacklogAPI.scala, oauth2/src/main/scala/skinny/oauth2/client/backlog/BacklogJPAPI.scala, oauth2/src/main/scala/skinny/oauth2/client/dropbox/DropboxAPI.scala, oauth2/src/main/scala/skinny/oauth2/client/facebook/FacebookGraphAPI.scala, oauth2/src/main/scala/skinny/oauth2/client/github/GitHubAPI.scala, oauth2/src/main/scala/skinny/oauth2/client/google/GooglePlusAPI.scala, oauth2/src/main/scala/skinny/oauth2/client/typetalk/TypetalkAPI.scala, project/Build.scala, test/src/main/scala/skinny/test/MockControllerBase.scala, yeoman-generator-skinny/app/templates/project/Build.scala
This pull request brings a breaking change to JSONStringOps.
before: `JSONStringOps#fromJSONString[A](String): Option[A]`
after: `JSONStringOps#fromJSONString[A](String): scala.util.Try[A]`
- JSONStringOps#fromJSONString returns Try instead of Option
- SkinnyMicroBase doesn't provide thread-local request/response by default
=> Bump skinny-micro to 0.9.11

http-client/src/main/scala/skinny/http/HTTP.scala
It would be better if library users can instantiate HTTP object especially when testing (e.g. mocking it).
=> Enable HTTP to instantiate especially when testing

framework/src/main/scala/skinny/bootstrap/NOOPServletContext.scala, framework/src/main/scala/skinny/bootstrap/SkinnyLifeCycle.scala, framework/src/main/scala/skinny/controller/feature/CSRFProtectionFeature.scala, framework/src/main/scala/skinny/routing/RichRoute.scala, framework/src/test/scala/skinny/bootstrap/NOOPServletContextSpec.scala, project/Build.scala, run_skinny-blank-app_test.sh, skinny-blank-app/project/Build.scala, skinny-blank-app/skinny, skinny-blank-app/skinny.bat, skinny-blank-app/task/src/main/scala/TaskRunner.scala
This pull request newly adds `skinny routes` command to call skinny-micro's new RouteRegistry API. https://github.com/skinny-framework/skinny-micro/pull/19
Output example:
https://travis-ci.org/seratch/skinny-framework/jobs/101226394#L4059
```
GET /?
GET /admin/help
GET /admin/sandbox/api
GET /assets/css/*
GET /assets/js/*
GET /help
GET /members
POST  /members
GET /members.:ext
POST  /members.:ext
GET /members/
POST  /members/
DELETE  /members/:id
GET /members/:id
PATCH /members/:id
POST  /members/:id
PUT /members/:id
DELETE  /members/:id.:ext
GET /members/:id.:ext
PATCH /members/:id.:ext
POST  /members/:id.:ext
PUT /members/:id.:ext
GET /members/:id/edit
GET /members/new
```
=> Add skinny routes command to display available routes information

common/src/main/scala/skinny/I18n.scala, common/src/main/scala/skinny/util/TypesafeConfigReader.scala, common/src/test/resources/messages.conf, common/src/test/scala/skinny/I18nSpec.scala, validator/src/test/scala/skinny/validator/MessagesSpec.scala
typesafe-config always places priority on system properties when loading config values.
https://github.com/typesafehub/config#standard-behavior
This pull request changes the behavior only for i18n messages.
=> Remove system properties from i18n messages

example/src/test/scala/controller/RootControllerSpec.scala, test/src/main/scala/skinny/test/MockHttpServletRequest.scala
```
[info]     java.lang.NullPointerException:
[info]     at skinny.session.SkinnyHttpSession$.getOrCreateJDBCImpl(SkinnyHttpSession.scala:43)
[info]     at skinny.session.SkinnyHttpSession$.getOrCreate(SkinnyHttpSession.scala:35)
[info]     at skinny.filter.SkinnySessionFilterBase$class.initializeSkinnySession(SkinnySessionFilterBase.scala:36)
[info]     at controller.RootController.initializeSkinnySession(RootController.scala:8)
[info]     at skinny.filter.SkinnySessionFilterBase$$anonfun$skinnySession$1.apply(SkinnySessionFilterBase.scala:55)
[info]     at skinny.filter.SkinnySessionFilterBase$$anonfun$skinnySession$1.apply(SkinnySessionFilterBase.scala:55)
[info]     at scala.Option.getOrElse(Option.scala:121)
[info]     at skinny.filter.SkinnySessionFilterBase$class.skinnySession(Skin …
```
=> Fixed NullPointerException in MockController with SkinnySessionFilter

project/Build.scala, skinny-blank-app/skinny, skinny-blank-app/skinny.bat
- skinny-micro 1.0.5
- sfl4j-api 1.7.21
- commons-io 2.5
- joda-time 2.9.3
- Scala.js 0.6.9
=> Bump dependencies

common/src/main/scala/skinny/activeimplicits/AllImplicits.scala, common/src/main/scala/skinny/activeimplicits/InflectorImplicits.scala, common/src/main/scala/skinny/nlp/Inflector.scala, common/src/test/scala/skinny/activeimplicits/AllImplicitsSpec.scala, common/src/test/scala/skinny/activeimplicits/InflectorImplicitsSpec.scala, project/Build.scala, skinny-blank-app/project/Build.scala, task/src/main/scala/skinny/task/generator/CodeGenerator.scala, task/src/main/scala/skinny/task/generator/ModelGenerator.scala, task/src/main/scala/skinny/task/generator/ReverseGenerator.scala, task/src/main/scala/skinny/task/generator/ReverseModelAllGenerator.scala, task/src/main/scala/skinny/task/generator/ReverseModelGenerator.scala, task/src/main/scala/skinny/task/generator/ReverseScaffoldAllGenerator.scala, task/src/main/scala/skinny/task/generator/ReverseScaffoldGenerator.scala, task/src/main/scala/skinny/task/generator/ScaffoldGenerator.scala, task/src/test/scala/skinny/task/generator/ReverseModelAllGeneratorSpec.scala, task/src/test/scala/skinny/task/generator/ReverseScaffoldAllGenerator_InflectorSpec.scala, task/src/test/scala/skinny/task/generator/ReverseScaffoldAllGenerator_reservedWordsSpec.scala
This pull request brings the following things:
=> Enable doing `skinny g reverse-scaffold-all` toward existing Rails applications

build.sbt, example/src/main/scala/controller/CommentsController.scala, framework/src/main/scala/skinny/controller/SkinnyApiResourceActions.scala, run_skinny-blank-app_test.sh, skinny-blank-app/build.sbt, task/src/main/scala/skinny/task/generator/ScaffoldGenerator.scala, task/src/main/scala/skinny/task/generator/ScaffoldJadeGenerator.scala, task/src/main/scala/skinny/task/generator/ScaffoldScamlGenerator.scala, task/src/main/scala/skinny/task/generator/ScaffoldSspGenerator.scala, task/src/test/scala/skinny/task/generator/ScaffoldGeneratorSpec.scala, task/src/test/scala/skinny/task/generator/ScaffoldJadeGeneratorSpec.scala, task/src/test/scala/skinny/task/generator/ScaffoldScamlGeneratorSpec.scala, task/src/test/scala/skinny/task/generator/ScaffoldSspGeneratorSpec.scala
This pull request enables appending namespace to resource name to messages.conf if exists. 
There may be a possibility to have same resource names under another namespace. In such cases,  making resource names unique by prepending namespace to it would be fine. The similar fix is already done with `src/test/resources/factories.conf` for factory-girl module.
=> Apply namespace on resource name in messages.conf

.travis.yml, assets/src/main/scala/skinny/assets/CoffeeScriptCompiler.scala, assets/src/main/scala/skinny/assets/LessCompiler.scala, assets/src/main/scala/skinny/assets/ReactJSXCompiler.scala, assets/src/main/scala/skinny/assets/SassCompiler.scala, assets/src/test/scala/skinny/assets/SassCompilerSpec.scala, build.sbt, common/src/main/scala/skinny/ScalaVersion.scala, example/src/test/scala/integrationtest/AssetsSpec.scala, travis.sh
This pull request re-enables Travis builds for Scala 2.12. 
Somehow, `scala.sys.process` stuck for Less, Sass processes. Since skinny just use it for on-the-fly assets precompilation for local development, I've disabled external processes in Scala for now.
=> Re-enable Scala 2.12 CI

framework/src/main/scala/skinny/session/servlet/SkinnyHttpRequestWrapper.scala, test/src/test/scala/skinny/controller/SessionInjectorControllerSpec.scala
`skinny.session.servlet.SkinnyHttpRequestWrapper` must be an instance of `HttpServletRequestWrapper`.
Jetty 9.3 checks the actual type:
https://github.com/eclipse/jetty.project/blob/33eb768d6972fe67b5058c96941645cb03fea6e7/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L148-L164
=> Fix a bug that affects compatibility with Jetty 9.3 in skinny-session

build.sbt, skinny-blank-app/build.sbt
A workaround for #340 was found. This pull request enables to use Scala 2.12 by default with it.
=> Enable to use Scala 2.12 by default

framework/src/main/scala/skinny/controller/SkinnyApiResourceActions.scala, framework/src/main/scala/skinny/controller/SkinnyResourceActions.scala
Overriding `messageResourceName` in `SkinnyResource` is ignored. This pull request fixes the bug.
=> Fix an bug on customizing validation messages in SkinnyResource

build.sbt, project/plugins.sbt, skinny-blank-app/build.sbt, skinny-blank-app/project/plugins.sbt, skinny-blank-app/skinny, skinny-blank-app/skinny.bat
This pull request bumps the following dependencies for 2.3.3 release.
- Jetty 9.3.14 -> 9.3.15
- Skinny Micro 1.2.1 -> 1.2.2
- scala-parser-combinators 1.0.4 -> 1.0.5
- joda-time 2.9.6 -> 2.9.7
- sbt-servlet-plugin 2.1.0 -> 2.1.1
- scala.js 0.6.13 -> 0.6.14
- Scala version for Scala.js 2.11.8 -> 2.12.1
=> Bump jetty, scalajs, skinny-micro, etc..

common/src/main/scala/skinny/ParamType.scala, common/src/test/scala/skinny/ParamTypeSpec.scala
This pull request introduces new ParamType to allow inserting nullable String values into a database. 
The existing ParamType.String inserts empty string if user doesn't specify value. Both of the patterns exist in the wild. We don't change the deafult behavior this time but most users prefer using NullableString by default. we might consider changing the default one in the future.
=> Add ParamType.NullableString

build.sbt, orm/src/main/scala/skinny/orm/SkinnyMapperBase.scala, orm/src/main/scala/skinny/orm/feature/AssociationsFeature.scala, orm/src/main/scala/skinny/orm/feature/NoIdFinderFeature.scala, orm/src/test/scala/skinny/orm/SkinnyORMSpec.scala
I found joins finder is can't "countBy".
This pull request is correspond patch to that.
=> Enable #countBy method also for joins queries

build.sbt, common/src/main/scala/skinny/nlp/SkinnyJapaneseAnalyzerFactory.scala, project/plugins.sbt, skinny-blank-app/build.sbt, skinny-blank-app/project/plugins.sbt
This pull request upgrades the following:
- scalikejdbc 3.0 -> 3.1
- kuromoji 6.6 -> 7.0
If the upgrades work, I will release 2.5.0 with the changes.
=> Bump ScalikeJDBC, Kuromoji versions

orm/src/main/scala/skinny/orm/SkinnyMapperBase.scala, orm/src/main/scala/skinny/orm/feature/NoIdQueryingFeature.scala, orm/src/main/scala/skinny/orm/feature/QueryingFeature.scala, orm/src/main/scala/skinny/orm/feature/package.scala, orm/src/test/scala/test009/Spec.scala
This pull request fixes an existing bug where the `defaultOrderings` is ignored by querying APIs. 
Actually, this change may affect existing applications. But I believe changing the behavior should be straight-forward for everybody.
=> Fix a bug where defaultOrderings doesn't work for querying API

assets/src/main/scala/skinny/assets/CoffeeScriptCompiler.scala, assets/src/main/scala/skinny/assets/LessCompiler.scala, assets/src/main/scala/skinny/assets/ReactJSXCompiler.scala, assets/src/main/scala/skinny/assets/SassCompiler.scala
dropped Scala 2.10 support since https://github.com/skinny-framework/skinny-framework/commit/c734b1cd7072858e175e60ee770b74e2a64954ee
=> fix deprecation warnings. s/lines/lineStream/

framework/src/main/scala/skinny/controller/feature/SkinnyControllerCommonBase.scala
- https://github.com/json4s/json4s/commit/5dc445ea3499ce5170c019e8bd331b7ddc75f4c1#diff-068ccf519551985c71c4a8dc08c54094R174
- https://github.com/json4s/json4s/blob/357110b7e7668f95c21aa2f5d4779fcf6b47eee7/core/src/main/scala/org/json4s/Xml.scala#L174
```
[warn] /home/travis/build/skinny-framework/skinny-framework/framework/src/main/scala/skinny/controller/feature/SkinnyControllerCommonBase.scala:125: match may not be exhaustive.
[warn] It would fail on the following input: JSet(_)
[warn]     def _toXml(name: String, json: JValue): NodeSeq = json match {
[warn]                                                       ^
```
=> fix "match may not be exhaustive" warning

build.sbt, orm/src/main/scala/skinny/orm/feature/DynamicTableNameFeature.scala, orm/src/main/scala/skinny/orm/feature/JoinsFeature.scala, project/plugins.sbt, travis.sh
In this commit, I've upgraded the following libs (only patch versions):
* mockito
* flyway-core
* freemarker
* scalafmt
Also, I've decided to get rid of net-sbt-scalafmt because the sbt plugin is no longer actively maintained.
As the successor, I switched to sbt-scalafmt.
=> Bump deps' version, get rid of neo-sbt-scalafmt

.travis.yml, build.sbt
This pull request bumps Scala 2.12 to 2.12.7. Also, I've added more JDKs to test.
=> Bump Scala 2.12, update JDKs for Travis builds

validator/src/main/scala/skinny/validator/BuiltinValidationRules.scala, validator/src/test/scala/skinny/validator/dateFormatSpec.scala, validator/src/test/scala/skinny/validator/dateTimeFormatSpec.scala
Input strings like "-06-12" or "-06-12 03:04:05", which are invalid but acceptable for Joda-Time, not to pass the validation.
Joda-Time accepts them as "-0006-12-01T03:04:05". It is generally not what was intended.
=> invalid DateTime expression not to pass
